/**
 * Milestones_All_Plans
 */

package edu.umn.csci5801.model;

public enum Milestones_All_Plans {
	// Common milestones
	DPF_SUBMITTED,
	DPF_APPROVED,
	THESIS_COMMITTEE_APPOINTED,
	GRADUATION_PACKET_REQUESTED,
	THESIS_SUBMITTED,
	THESIS_APPROVED,
	DEFENSE_PASSED,
	
	// Plan B
	PROJECT_COMMITTEE_APPOINTED,
	
	// Plan C Unique
	TRACKING_FORM_SUBMITTED,
	TRACKING_FORM_APPROVED,
	
	// PhD Unique
	PRELIM_COMMITTEE_APPOINTED,
	WRITTEN_PE_SUBMITTED,
	WRITTEN_PE_APPROVED,
	ORAL_PE_PASSED,
	PROPOSAL_PASSED;
}